"""empty message

Revision ID: 4924d02d0528
Revises: bd7c1c85735
Create Date: 2015-08-02 14:16:45.666182

"""

# revision identifiers, used by Alembic.
revision = '4924d02d0528'
down_revision = 'bd7c1c85735'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
