"""empty message

Revision ID: a950a8d3451
Revises: 4924d02d0528
Create Date: 2015-08-05 12:08:43.525429

"""

# revision identifiers, used by Alembic.
revision = 'a950a8d3451'
down_revision = '4924d02d0528'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
